version: '3.4'

services:
  postgres.data:
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
    volumes:
      - postgresdata-volume:/var/lib/postgresql/data
    ports:
      - "55432:5432"
      
  testprogrammationconformit:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"

volumes:
  postgresdata-volume: